### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by trdwll** [AverageDemo/Pesticide#1]
- [ ] In comments allow users to reference other issues, for example #XX-123 would embed as /issue/XX-123 etc
- [ ] In comments allow users to tag other users, for example like here on GitHub @AverageDemo .
- [ ] Prefix issues as project abbreviation such as MyProject would be MP-123
- [ ] Inline tools for staff for example moderation tools like close issue or hide issue
- [ ] Assign specific developers to an issue if they're apart of the group that the issue was posted in
- [ ] Add issues to a target release version, for example MP-1, MP-2, and MP-3 are targeted for Release 1.0. MP-1 and MP-2 are completed so show a progressbar at 66.6% since MP-3 is still open.
- [ ] Allow file uploads such as images and text files

Let me know what you think about these suggestions. I'm not aware if you've added any of them already or not.

**Comment by AverageDemo** [comment]
I definitely like all of these suggestions. They'll all be added once I finish the core functionality properly.
